from test.test_case import MkdirTestCase

class TestFunctions(MkdirTestCase):

    def test_functions(self):
        expected = (
            {'name': '_init', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199632},
            {'name': '_start', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200752},
            {'name': 'call_gmon_start', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4200796},
            {'name': '__do_global_dtors_aux', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4200832},
            {'name': 'frame_dummy', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200944},
            {'name': 'emit_mandatory_arg_note', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4200980},
            {'name': 'emit_ancillary_info', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4201027},
            {'name': 'emit_try_help', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4201314},
            {'name': 'usage', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4201376},
            {'name': 'announce_mkdir', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4201581},
            {'name': 'make_ancestor', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4201666},
            {'name': 'process_dir', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4201771},
            {'name': 'main', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4201892},
            {'name': 'prog_fprintf', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4202644},
            {'name': 'close_stdout_set_file_name', 'args': 'unknown',
             'retval': 'unknown', 'offset': 4202892},
            {'name': 'close_stdout_set_ignore_EPIPE', 'args': 'unknown',
             'retval': 'unknown', 'offset': 4202913},
            {'name': 'close_stdout', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4202934},
            {'name': 'last_component', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4203172},
            {'name': 'base_len', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4203277},
            {'name': 'make_dir_parents', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4203376},
            {'name': 'octal_to_mode', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4204436},
            {'name': 'make_node_op_equals', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4204448},
            {'name': 'mode_compile', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4204540},
            {'name': 'mode_create_from_ref', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4205604},
            {'name': 'mode_adjust', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4205675},
            {'name': 'set_program_name', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206084},
            {'name': 'clone_quoting_options', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206360},
            {'name': 'get_quoting_style', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206433},
            {'name': 'set_quoting_style', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206463},
            {'name': 'set_char_quoting', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206499},
            {'name': 'set_quoting_flags', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206641},
            {'name': 'set_custom_quoting', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206692},
            {'name': 'quoting_options_from_style', 'args': 'unknown',
             'retval': 'unknown', 'offset': 4206782},
            {'name': 'gettext_quote', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4206902},
            {'name': 'quotearg_buffer_restyled', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4207070},
            {'name': 'quotearg_buffer', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4209937},
            {'name': 'quotearg_alloc', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4210097},
            {'name': 'quotearg_alloc_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4210147},
            {'name': 'quotearg_free', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4210447},
            {'name': 'quotearg_n_options', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4210612},
            {'name': 'quotearg_n', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4211233},
            {'name': 'quotearg_n_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211276},
            {'name': 'quotearg', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4211320},
            {'name': 'quotearg_mem', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4211351},
            {'name': 'quotearg_n_style', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211390},
            {'name': 'quotearg_n_style_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211455},
            {'name': 'quotearg_style', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211518},
            {'name': 'quotearg_style_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211554},
            {'name': 'quotearg_char_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211598},
            {'name': 'quotearg_char', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4211746},
            {'name': 'quotearg_colon', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211788},
            {'name': 'quotearg_colon_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211819},
            {'name': 'quotearg_n_custom', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211861},
            {'name': 'quotearg_n_custom_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211915},
            {'name': 'quotearg_custom', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4212066},
            {'name': 'quotearg_custom_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4212113},
            {'name': 'quote_n_mem', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212171},
            {'name': 'quote_mem', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212215},
            {'name': 'quote_n', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212254},
            {'name': 'quote', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212295},
            {'name': 'savewd_init', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212328},
            {'name': 'savewd_errno', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212348},
            {'name': 'savewd_save', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212383},
            {'name': 'savewd_chdir', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212720},
            {'name': 'savewd_restore', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4213145},
            {'name': 'savewd_finish', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4213490},
            {'name': 'savewd_delegating', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4213618},
            {'name': 'savewd_process_files', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4213662},
            {'name': 'getcon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214004},
            {'name': 'freecon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214034},
            {'name': 'getfscreatecon', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214044},
            {'name': 'setfscreatecon', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214074},
            {'name': 'matchpathcon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214104},
            {'name': 'getfilecon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214141},
            {'name': 'lgetfilecon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214175},
            {'name': 'fgetfilecon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214209},
            {'name': 'setfilecon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214242},
            {'name': 'lsetfilecon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214276},
            {'name': 'fsetfilecon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214310},
            {'name': 'security_check_context', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214343},
            {'name': 'security_check_context_raw', 'args': 'unknown',
             'retval': 'unknown', 'offset': 4214373},
            {'name': 'setexeccon', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4214403},
            {'name': 'security_compute_create', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214433},
            {'name': 'matchpathcon_init_prefix', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214477},
            {'name': 'version_etc_arn', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214512},
            {'name': 'version_etc_ar', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4215994},
            {'name': 'version_etc_va', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4216097},
            {'name': 'version_etc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216314},
            {'name': 'emit_bug_reporting_address', 'args': 'unknown',
             'retval': 'unknown', 'offset': 4216496},
            {'name': 'xnmalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216604},
            {'name': 'xnrealloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216666},
            {'name': 'x2nrealloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216742},
            {'name': 'xcharalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216907},
            {'name': 'xmalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216933},
            {'name': 'xrealloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216986},
            {'name': 'x2realloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217083},
            {'name': 'xzalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217125},
            {'name': 'xcalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217168},
            {'name': 'xmemdup', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217225},
            {'name': 'xstrdup', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217277},
            {'name': 'xalloc_die', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217352},
            {'name': 'rpl_vfprintf', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217408},
            {'name': 'c_strcasecmp', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217772},
            {'name': 'close_stream', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217896},
            {'name': 'open_safer', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4218036},
            {'name': 'get_charset_aliases', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4218312},
            {'name': 'locale_charset', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4219700},
            {'name': 'mkancesdirs', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4219988},
            {'name': 'dirchownmod', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4220440},
            {'name': 'fd_safer', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221012},
            {'name': 'rpl_fclose', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221092},
            {'name': 'clear_ungetc_buffer_preserving_position', 'args':
                'unknown', 'retval': 'unknown', 'offset': 4221276},
            {'name': 'rpl_fflush', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221327},
            {'name': 'rpl_fseeko', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221404},
            {'name': 'fseterr', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221588},
            {'name': 'decimal_point_char', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4221616},
            {'name': 'is_infinite_or_zerol', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4221665},
            {'name': 'vasnprintf', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221734},
            {'name': 'c_isascii', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4235744},
            {'name': 'c_isalnum', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4235777},
            {'name': 'c_isalpha', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4235832},
            {'name': 'c_isblank', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4235875},
            {'name': 'c_iscntrl', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4235908},
            {'name': 'c_isdigit', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4235945},
            {'name': 'c_islower', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4235978},
            {'name': 'c_isgraph', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236011},
            {'name': 'c_isprint', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236044},
            {'name': 'c_ispunct', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236077},
            {'name': 'c_isspace', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236144},
            {'name': 'c_isupper', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236201},
            {'name': 'c_isxdigit', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236234},
            {'name': 'c_tolower', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236289},
            {'name': 'c_toupper', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236321},
            {'name': 'dup_safer', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236356},
            {'name': 'xsum', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236396},
            {'name': 'xsum3', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236448},
            {'name': 'xsum4', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236504},
            {'name': 'xmax', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236579},
            {'name': 'rpl_fcntl', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236608},
            {'name': 'rpl_isnanl', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4237312},
            {'name': 'printf_fetchargs', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4237404},
            {'name': 'printf_parse', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4239424},
            {'name': '__libc_csu_init', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4244864},
            {'name': '__libc_csu_fini', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4245008},
            {'name': 'atexit', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4245024},
            {'name': '__stat', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4245056},
            {'name': '__fstat', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4245072},
            {'name': '__do_global_ctors_aux', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4245088},
            {'name': '_fini', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4245144},
            {'name': 'func_00401800', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200448},
            {'name': 'func_00401900', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200704},
            {'name': 'set_program_name', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206084},
            {'name': 'func_004017e0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200416},
            {'name': 'c_tolower', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236289},
            {'name': 'xalloc_die', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217352},
            {'name': 'func_00401860', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200544},
            {'name': 'func_004015c0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199872},
            {'name': 'func_00401760', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200288},
            {'name': '_init', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199632},
            {'name': 'func_00401710', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200208},
            {'name': 'func_00401610', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199952},
            {'name': 'func_004015d0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199888},
            {'name': 'func_00401670', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200048},
            {'name': 'func_004018b0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200624},
            {'name': 'dirchownmod', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4220440},
            {'name': 'xnmalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216604},
            {'name': 'quote_n', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212254},
            {'name': 'func_00401920', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200736},
            {'name': 'func_00401530', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199728},
            {'name': 'quotearg_char', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4211746},
            {'name': 'xmax', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236579},
            {'name': 'func_004017d0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200400},
            {'name': 'vasnprintf', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221734},
            {'name': 'close_stream', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217896},
            {'name': 'clear_ungetc_buffer_preserving_position', 'args':
                'unknown', 'retval': 'unknown', 'offset': 4221276},
            {'name': 'emit_mandatory_arg_note', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4200980},
            {'name': 'func_00401630', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199984},
            {'name': 'locale_charset', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4219700},
            {'name': 'gettext_quote', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4206902},
            {'name': 'quotearg_n_options', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4210612},
            {'name': 'setfscreatecon', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214074},
            {'name': 'func_00401740', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200256},
            {'name': 'func_004018e0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200672},
            {'name': 'emit_ancillary_info', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4201027},
            {'name': 'dup_safer', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236356},
            {'name': 'func_00401810', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200464},
            {'name': 'rpl_isnanl', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4237312},
            {'name': 'quote', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212295},
            {'name': 'func_00401840', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200512},
            {'name': 'xcharalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216907},
            {'name': 'quotearg_n_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211276},
            {'name': 'make_dir_parents', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4203376},
            {'name': 'func_00401550', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199760},
            {'name': 'mkancesdirs', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4219988},
            {'name': 'printf_parse', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4239424},
            {'name': 'rpl_vfprintf', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217408},
            {'name': 'func_004016b0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200112},
            {'name': 'call_gmon_start', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4200796},
            {'name': 'func_00401730', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200240},
            {'name': '__do_global_ctors_aux', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4245088},
            {'name': 'func_00401910', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200720},
            {'name': 'emit_try_help', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4201314},
            {'name': 'func_004017b0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200368},
            {'name': 'set_custom_quoting', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206692},
            {'name': 'xmalloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216933},
            {'name': 'func_00401830', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200496},
            {'name': 'savewd_init', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212328},
            {'name': 'mode_adjust', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4205675},
            {'name': 'xsum', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236396},
            {'name': 'announce_mkdir', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4201581},
            {'name': 'func_00401520', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199712},
            {'name': 'func_00401870', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200560},
            {'name': 'savewd_delegating', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4213618},
            {'name': 'func_004015a0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199840},
            {'name': 'quotearg_n_style', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211390},
            {'name': 'func_00401620', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199968},
            {'name': 'octal_to_mode', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4204436},
            {'name': 'func_004016a0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200096},
            {'name': 'savewd_errno', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212348},
            {'name': 'func_00401650', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200016},
            {'name': 'func_00401720', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200224},
            {'name': 'func_00401580', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199808},
            {'name': 'func_00401640', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200000},
            {'name': 'func_004017a0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200352},
            {'name': 'rpl_fcntl', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236608},
            {'name': 'func_00401820', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200480},
            {'name': 'xmemdup', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217225},
            {'name': 'func_004018a0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200608},
            {'name': 'version_etc_va', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4216097},
            {'name': 'quotearg_char_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211598},
            {'name': 'rpl_fflush', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221327},
            {'name': 'func_00401690', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200080},
            {'name': 'func_00401590', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199824},
            {'name': 'prog_fprintf', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4202644},
            {'name': 'quotearg_n_custom', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211861},
            {'name': '__fstat', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4245072},
            {'name': 'savewd_restore', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4213145},
            {'name': 'xrealloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216986},
            {'name': 'version_etc_arn', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4214512},
            {'name': 'savewd_process_files', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4213662},
            {'name': 'savewd_save', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212383},
            {'name': 'make_node_op_equals', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4204448},
            {'name': 'savewd_chdir', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212720},
            {'name': 'func_00401790', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200336},
            {'name': 'set_char_quoting', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4206499},
            {'name': 'last_component', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4203172},
            {'name': 'x2nrealloc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216742},
            {'name': 'func_00401890', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200592},
            {'name': 'is_infinite_or_zerol', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4221665},
            {'name': 'c_strcasecmp', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4217772},
            {'name': 'func_00401500', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199680},
            {'name': 'func_004015b0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199856},
            {'name': 'fseterr', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221588},
            {'name': 'open_safer', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4218036},
            {'name': 'func_00401600', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199936},
            {'name': '__stat', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4245056},
            {'name': 'func_00401680', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200064},
            {'name': 'fd_safer', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221012},
            {'name': 'func_00401700', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200192},
            {'name': 'quoting_options_from_style', 'args': 'unknown',
             'retval': 'unknown', 'offset': 4206782},
            {'name': 'func_00401750', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200272},
            {'name': 'func_004016c0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200128},
            {'name': 'usage', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4201376},
            {'name': 'func_00401780', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200320},
            {'name': 'quotearg_n_custom_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211915},
            {'name': 'quotearg_n', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4211233},
            {'name': 'get_charset_aliases', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4218312},
            {'name': 'quotearg_colon', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211788},
            {'name': 'func_00401880', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200576},
            {'name': 'quote_n_mem', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4212171},
            {'name': 'func_00401510', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199696},
            {'name': 'func_00401850', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200528},
            {'name': 'func_004016d0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200144},
            {'name': 'func_00401570', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199792},
            {'name': '__do_global_dtors_aux', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4200832},
            {'name': 'func_004015f0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199920},
            {'name': 'xsum4', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4236504},
            {'name': 'rpl_fclose', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221092},
            {'name': 'rpl_fseeko', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4221404},
            {'name': 'func_004016f0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200176},
            {'name': 'quotearg_buffer_restyled', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4207070},
            {'name': 'func_004015e0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199904},
            {'name': 'func_004018d0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200656},
            {'name': 'quotearg_alloc_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4210147},
            {'name': 'func_004017f0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200432},
            {'name': 'printf_fetchargs', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4237404},
            {'name': 'func_004018f0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200688},
            {'name': 'func_00401560', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199776},
            {'name': 'savewd_finish', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4213490},
            {'name': 'frame_dummy', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200944},
            {'name': 'func_00401540', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4199744},
            {'name': 'atexit', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4245024},
            {'name': 'func_00401660', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200032},
            {'name': 'version_etc', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4216314},
            {'name': 'decimal_point_char', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4221616},
            {'name': 'mode_compile', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4204540},
            {'name': 'func_004016e0', 'args': 'unknown', 'retval': 'unknown',
             'offset': 4200160},
            {'name': 'quotearg_n_style_mem', 'args': 'unknown', 'retval':
                'unknown', 'offset': 4211455},
        )

        actual = self.project.Functions()

        for e, a in zip(expected, actual):
            self.assertDictEqual(e, a)
